export const RSS_FEEDS: ReadonlyArray<string> = [
  'https://huggingface.co/blog/feed.xml',
  'https://www.latent.space/feed',
  'https://blog.cloudflare.com/rss/',
  'https://stripe.com/blog/feed.rss',
  'https://discord.com/blog/rss.xml',
  'https://engineering.fb.com/feed/',
  'https://medium.com/feed/airbnb-engineering',
  'https://newsletter.pragmaticengineer.com/feed',
  'https://blog.bytebytego.com/feed',
  'https://newsletter.systemdesign.one/feed',
  'https://github.blog/feed/',
  'https://slack.engineering/feed/',
  'https://blog.google/technology/ai/rss/',
  'https://stackoverflow.blog/feed/',
  'https://medium.com/feed/pinterest-engineering',
  'https://engineering.atspotify.com/feed/',
  'https://techcrunch.com/category/artificial-intelligence/feed/',
  'https://blogs.nvidia.com/feed/',
  'https://magazine.sebastianraschka.com/feed',
  'https://www.federalreserve.gov/feeds/press_all.xml',
  'https://www.federalreserve.gov/feeds/speeches.xml',
  'https://www.sec.gov/news/pressreleases.rss',
  'https://feeds.marketwatch.com/marketwatch/topstories/',
  'https://www.cnbc.com/id/100003114/device/rss/rss.html',
  'https://www.investing.com/rss/news_25.rss',
  'https://www.investing.com/rss/news_356.rss',
  'https://www.benzinga.com/feed',
  'https://www.fool.com/feeds/index.aspx',
  'https://moxie.foxbusiness.com/google-publisher/markets.xml',
  'https://www.calculatedriskblog.com/feeds/posts/default',
  'https://ritholtz.com/feed/',
  'https://wolfstreet.com/feed/',
  'https://thefelderreport.com/feed/',
  'https://heisenbergreport.com/feed/',
  'https://mishtalk.com/feed/',
  'https://marginalrevolution.com/feed',
  'https://www.netinterest.co/feed',
  'https://moontower.substack.com/feed',
  'https://www.investing.com/rss/news_95.rss',
  'https://econbrowser.com/feed',
  'https://thelongview.substack.com/feed',

  // Reddit subreddits via RSS (public, no auth, different rate-limit layer
  // than /search.json — survives cloud-egress filtering that 403s the API).
  // Goes into the global pool; embedding similarity in the job's RAG step
  // surfaces items relevant to each theme.
  'https://www.reddit.com/r/MachineLearning/new/.rss',
  'https://www.reddit.com/r/LocalLLaMA/new/.rss',
  'https://www.reddit.com/r/OpenAI/new/.rss',
  'https://www.reddit.com/r/ClaudeAI/new/.rss',
  'https://www.reddit.com/r/singularity/new/.rss',
  'https://www.reddit.com/r/programming/new/.rss',
  'https://www.reddit.com/r/ExperiencedDevs/new/.rss',
  'https://www.reddit.com/r/cscareerquestions/new/.rss',
  'https://www.reddit.com/r/stocks/new/.rss',
  'https://www.reddit.com/r/investing/new/.rss',
  'https://www.reddit.com/r/Economics/new/.rss',
  'https://www.reddit.com/r/wallstreetbets/new/.rss',
];
